import { missingCredentialsResponse, resolveCredentials } from "@/lib/api-credentials";
import { fetchSiteFiles } from "@/lib/github";
import JSZip from "jszip";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

export async function GET(
  request: Request,
  context: { params: Promise<{ sessionId: string }> },
) {
  const { sessionId } = await context.params;

  if (!sessionId?.trim()) {
    return NextResponse.json({ error: "Missing sessionId" }, { status: 400 });
  }

  const credentials = resolveCredentials(request);
  if (!credentials) {
    return missingCredentialsResponse();
  }

  try {
    const files = await fetchSiteFiles(sessionId, {
      githubToken: credentials.githubToken,
      templateRepoUrl: credentials.templateRepoUrl,
      templateRepoRef: credentials.templateRepoRef,
    });

    if (!files) {
      return NextResponse.json({ error: "Site not found yet" }, { status: 404 });
    }

    const zip = new JSZip();
    zip.file("index.html", files.html);
    zip.file("styles.css", files.css || "/* No styles */");
    zip.file("script.js", files.js || "// No scripts");
    zip.file(
      "README.txt",
      [
        "Generated by Cursor SDK Web",
        "https://github.com/AppleLamps/cursor-sdk-web",
        "",
        "Open index.html in your browser or deploy to any static host.",
      ].join("\n"),
    );

    const buffer = await zip.generateAsync({ type: "arraybuffer" });

    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="site-${sessionId.slice(0, 8)}.zip"`,
      },
    });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Export failed" },
      { status: 500 },
    );
  }
}
